### ISSUE TITLE
In asp core 2.0 data should be serialized to xml format instead of simple text.

### ISSUE THREAD

**Issue by szykov** [shawnwildermuth/RssSyndication#6]
The workaround:

```
...
var rss = feed.Serialize();

XmlDocument xml = new XmlDocument();
xml.LoadXml(rss);

return this.Ok(xml);
```

**Comment by shawnwildermuth** [comment]
I am confused, can you explain the use case you're talking about?

**Comment by szykov** [comment]
Hi Shawn. It took a while :))) I hardly remember what it was. As far as I remember after migration to net core 2.0 it started to return a string instead of pure XML. So I had to convert it to the needed format explicitly.

Love your library and your work. Thanks.

**Comment by shawnwildermuth** [comment]
Sorry it took so long. I'm trying to get github notifications to popup.
