### ISSUE TITLE
Lastest version as NuGet?

### ISSUE THREAD

**Issue by Corstiaan84** [shawnwildermuth/RssSyndication#8]
Hi,

Thanks for some awesome software!

By the looks of it, the current NuGet does not include the item enclosures, correct? Could you push a new NuGet version?

Will use the source for now.

Thanks!

**Comment by shawnwildermuth** [comment]
Yes, I've been on the road for four weeks, so it's on the list to get out quickly. Sorry about that.

**Comment by Corstiaan84** [comment]
No problem. Keep up the good work! 👍

**Comment by shawnwildermuth** [comment]
It's been updated in Nuget, might take an hour or two to update. New version (1.3)
